### ISSUE TITLE
verify Phone Number

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-register#12]
If a contact has uploaded a device number, it must be validated the phone number due a validation code.
The validation code is a short code.
The code is included in an SMS that is send to the given phone number.

**Comment by enkore** [comment]
From a verification flow perspective I'd say that this is what we want, since it'd be the least annoying kind of verification: Get an SMS, reply "okey-dokey" or "nopey-dopey" and be done with it.

![reverse sms verification](http://dh98h2q33pv9.cloudfront.net/images/sms2.png)

(from http://www.onverify.com/phone-verification-services )

**Comment by audax** [comment]
Resolved in #18 

If we need an sms gateway that is not supported by the library we use, we start a new ticket.
