### ISSUE TITLE
Research which verification services we can use

### ISSUE THREAD

**Issue by jasinai** [Qabel/qabel-register#7]
Since we don't want to send the verification e-mails and sms ourselves, we should search for services we could use.
I found https://www.twilio.com which can send sms.
Does someone know more services? Or is there a better way?

**Comment by dannywerner** [comment]
http://www.smskaufen.com has simple web interface and api to send sms. we charge a account and can send sms until the account balance is zero. the provider is in germany and exists many years. we have different kinds of sms, simple ... premium (faster), with or without own msisdn. if you charge more, the price per sms is lower... the prices between 0,019€ and 0,077€

smskaufen company is located near hannover (in herford)

Optional: The android application can watch for incomming sms and 'automatic' start action like send response to server (same way as whatsapp & co) so the user dont need do any action.

@jasinai: if you further investigate, pls looks if selected providers supports worldwide! sms delivery, with or without status

Alternative: If we want to SAVE MONEY, we can go to other way. The user must send a sms to our number. This can be handle by the named provider (smskaufen). We get a server call (to our register server) if we receive a sms. For Android, iam can add a function to send sms from app.

Pls don't hesitate to contact me for further infos.

**Comment by enkore** [comment]
From a verification flow perspective I'd say that this is what we want, since it'd be the least annoying kind of verification: Get an SMS, reply "okey-dokey" or "nopey-dopey" and be done with it.

![reverse sms verification](http://dh98h2q33pv9.cloudfront.net/images/sms2.png)

>  Needs number to send sms. Customer needs to reply to sms with his mobile.

(from http://www.onverify.com/phone-verification-services )

---

The next best thing would be to send an SMS containing a website to visit and a code to enter. This is obviously far more annoying to do, OTOH doesn't require as much support from the "SMS sending provider thing" (just need to send a SMS, no need to support complex flows on their end), which would make them more exchangeable. It also may make it easier to display additional information on the website (full fingerprint / QR, ...).

---

Services

- onverify
- https://docs.nexmo.com/
- https://www.twilio.com/sms/pricing/de
- ...

**Comment by enkore** [comment]
Costs (considering German mobiles):

- onverify: ~0.6-0.7 EUR / verification
- twilio: 0.07 EUR / SMS
- nexmo: 0.065 EUR / SMS (look who's underbidding the competition ;)
- others providers of this kind of service are also in this price range
- APIs are usually REST HTTP(S) and not too complex

**Comment by enkore** [comment]
- [x] use abstraction (preferably exisiting, django-sendsms)
- [x] twilio
